services:
  mongodb:
    image: mongo:latest
    container_name: parchamongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: parcha
      MONGO_INITDB_ROOT_PASSWORD: parcha
    volumes:
      - ./parchamongo:/data/db

  backend:
    image: parchabackend
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: parchabackend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongodb
