// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { usersId, type UsersId } from './Users';
import { z } from 'zod';

/** Identifier type for public.documents */
export type DocumentsId = string & { __brand: 'DocumentsId' };

/** Represents the table public.documents */
export default interface Documents {
  id: DocumentsId;

  userId: UsersId;

  extension: string;

  content: unknown;

  createdAt: Date;

  updatedAt: Date;

  title: string | null;
}

/** Represents the initializer for the table public.documents */
export interface DocumentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: DocumentsId;

  userId: UsersId;

  extension: string;

  content: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;

  title?: string | null;
}

/** Represents the mutator for the table public.documents */
export interface DocumentsMutator {
  id?: DocumentsId;

  userId?: UsersId;

  extension?: string;

  content?: unknown;

  createdAt?: Date;

  updatedAt?: Date;

  title?: string | null;
}

export const documentsId = z.string() as unknown as z.Schema<DocumentsId>;

export const documents = z.object({
  id: documentsId,
  userId: usersId,
  extension: z.string(),
  content: z.unknown(),
  createdAt: z.date(),
  updatedAt: z.date(),
  title: z.string().nullable(),
}) as unknown as z.Schema<Documents>;

export const documentsInitializer = z.object({
  id: documentsId.optional(),
  userId: usersId,
  extension: z.string(),
  content: z.unknown(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  title: z.string().optional().nullable(),
}) as unknown as z.Schema<DocumentsInitializer>;

export const documentsMutator = z.object({
  id: documentsId.optional(),
  userId: usersId.optional(),
  extension: z.string().optional(),
  content: z.unknown().optional(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  title: z.string().optional().nullable(),
}) as unknown as z.Schema<DocumentsMutator>;
