/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthGoogleCbImport } from './routes/auth/google/cb'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AuthIndexLazyImport = createFileRoute('/auth/')()
const DocumentsIdLazyImport = createFileRoute('/documents/$id')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthIndexLazyRoute = AuthIndexLazyImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/index.lazy').then((d) => d.Route))

const DocumentsIdLazyRoute = DocumentsIdLazyImport.update({
  path: '/documents/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/documents/$id.lazy').then((d) => d.Route))

const AuthGoogleCbRoute = AuthGoogleCbImport.update({
  path: '/auth/google/cb',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/google/cb': {
      id: '/auth/google/cb'
      path: '/auth/google/cb'
      fullPath: '/auth/google/cb'
      preLoaderRoute: typeof AuthGoogleCbImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  DocumentsIdLazyRoute,
  AuthIndexLazyRoute,
  AuthGoogleCbRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/documents/$id",
        "/auth/",
        "/auth/google/cb"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/documents/$id": {
      "filePath": "documents/$id.lazy.jsx"
    },
    "/auth/": {
      "filePath": "auth/index.lazy.tsx"
    },
    "/auth/google/cb": {
      "filePath": "auth/google/cb.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
