services:
  mongodb:
    image: mongo:latest
    container_name: parchamongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: parcha
      MONGO_INITDB_ROOT_PASSWORD: parcha
    volumes:
      - ./parchamongo:/data/db

  postgres:
    image: postgres:latest
    container_name: parchapostgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: parcha
      POSTGRES_PASSWORD: parcha
      POSTGRES_DB: parcha
    volumes:
      - ./parchapostgres:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d

  backend:
    image: parchabackend
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: parchabackend
    ports:
      - "8000:8000"
    volumes:
      - ../../packages/backend:/app
    env_file:
      - .env
    depends_on:
      - mongodb
      - postgres
